- create:
    - ~/.local/bin

- link:
    ~/.local/bin/pr-review.sh:
      path: bin/pr-review.sh
      relink: true
    ~/.local/bin/ollama-sync.sh:
      path: bin/ollama-sync.sh
      relink: true
