- link:
    /etc/ssh/sshd_config.d/sshd_custom_override.conf:
      create: true
      path: ssh/sshd/sshd_custom_override.conf

- clean: ['/etc/ssh/sshd_config.d']

- shell:
    - command: systemctl restart ssh
      description: Restarting SSH Daemon
      quiet: true
      stdout: true
      stderr: true
