- link:
    ~/.ssh/config:
      create: true
      path: ssh/config

    ~/.ssh/authorized_keys:
      create: true
      path: ssh/authorized_keys
      force: true
      # only copy the authorized_keys file if the environment variable
      # DOTBOT_SKIP_SSH_AUTHORIZED_FILE is not set
      if: '[ -z ${DOTBOT_SKIP_SSH_AUTHORIZED_FILE+x} ]'

    ~/.ssh/known_hosts_fixed:
      create: true
      path: ssh/known_hosts_fixed

    ~/.ssh/known_hosts_ansible:
      create: true
      path: ssh/known_hosts_ansible
      # only copy the Ansible known_hosts_ansible file if the environment variable
      # DOTBOT_SKIP_SSH_KNOWN_HOSTS_ANSIBLE_FILE is not set
      if: '[ -z ${DOTBOT_SKIP_SSH_KNOWN_HOSTS_ANSIBLE_FILE+x} ]'
