- link:
    ~/.zshrc:
      force: true
      path: shells/zsh/zshrc

- shell:
    - command: test ! -d $HOME/.oh-my-zsh && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || echo "Oh My Zsh already installed, skipping installation"
      description: Installing Oh My Zsh
      quiet: true
      stdout: true
      stderr: true
    # test if the github repo 'https://github.com/zsh-users/zsh-autosuggestions' 
    # is already cloned. If yes, pull latest changes. If not, clone it.
    - command: (test -d $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions && git -C $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions pull) || git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
      description: Adding zsh-autosuggestions plugin
      quiet: true
      stdout: false
      stderr: true
    # test if the github repo 'https://github.com/zsh-users/zsh-history-substring-search' 
    # is already cloned. If yes, pull latest changes. If not, clone it.
    - command: (test -d $HOME/.oh-my-zsh/custom/plugins/zsh-history-substring-search && git -C $HOME/.oh-my-zsh/custom/plugins/zsh-history-substring-search pull) || git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
      description: Adding zsh-history-substring-search plugin
      quiet: true
      stdout: false
      stderr: true
    # test if the github repo 'https://github.com/zsh-users/zsh-syntax-highlighting' 
    # is already cloned. If yes, pull latest changes. If not, clone it.
    - command: (test -d $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && git -C $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting pull) || git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
      description: Adding zsh-syntax-highlighting plugin
      quiet: true
      stdout: false
      stderr: true