
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# ZSH_THEME="agnoster"
# ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  #docker
  #git
  #ssh-agent
  #zsh-autosuggestions
  #zsh-syntax-highlighting
  zsh-autocomplete
  )

source $ZSH/oh-my-zsh.sh
