name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Qwen2.5-Coder 14B
    provider: ollama
    model: qwen2.5-coder:14b
    apiBase: http://10.10.1.100:11434
    roles:
      - chat
      - edit
      - apply
  - name: Qwen3.5 9B
    provider: ollama
    model: qwen3.5:9b
    apiBase: http://10.10.1.100:11434
    roles:
      - chat
      - edit
      - apply
  - name: Qwen2.5-Coder 1.5B
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    apiBase: http://10.10.1.100:11434
    roles:
      - autocomplete
